# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamoFireDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamoFireDemo

pod 'Alamofire'
pod 'SVProgressHUD'

  target 'AlamoFireDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamoFireDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
